[package]
name = "gen-eli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
japanese_law_xml_schema = "5.0.3"
tokio = { version = "1.48.0", features = ["full"] }
